name: Update Marketplace Catalog

on:
  push:
    branches:
      - main
    paths:
      - 'plugins/**'
  workflow_dispatch:

jobs:
  update-catalog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Generate marketplace catalog
        run: node scripts/generate-catalog.js

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code .claude-plugin/marketplace.json || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push if changed
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .claude-plugin/marketplace.json
          git commit -m "chore: update marketplace catalog [skip ci]"
          git push
